const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('desktopBridge', {
  platform: process.platform,
  versions: {
    chrome: process.versions.chrome,
    electron: process.versions.electron,
    node: process.versions.node,
  },
  loadState: () => ipcRenderer.invoke('ram:load-state'),
  unlockAccounts: (password) => ipcRenderer.invoke('ram:unlock-accounts', password),
  saveSetting: (payload) => ipcRenderer.invoke('ram:save-setting', payload),
  saveTheme: (payload) => ipcRenderer.invoke('ram:save-theme', payload),
  pickCustomClientSettings: () => ipcRenderer.invoke('ram:pick-custom-client-settings'),
  clearCustomClientSettings: () => ipcRenderer.invoke('ram:clear-custom-client-settings'),
  openReleasePage: () => ipcRenderer.invoke('ram:open-release-page'),
  updateAccount: (payload) => ipcRenderer.invoke('ram:update-account', payload),
  setAccountField: (payload) => ipcRenderer.invoke('ram:set-account-field', payload),
  removeAccountField: (payload) => ipcRenderer.invoke('ram:remove-account-field', payload),
  removeAccounts: (usernames) => ipcRenderer.invoke('ram:remove-accounts', usernames),
  sortAccounts: () => ipcRenderer.invoke('ram:sort-accounts'),
  saveLaunchForAccounts: (payload) => ipcRenderer.invoke('ram:save-launch-for-accounts', payload),
  copyAccountData: (payload) => ipcRenderer.invoke('ram:copy-account-data', payload),
  dumpAccountDetails: (payload) => ipcRenderer.invoke('ram:dump-account-details', payload),
  importCookie: (payload) => ipcRenderer.invoke('ram:import-cookie', payload),
  importCookiesBulk: (payload) => ipcRenderer.invoke('ram:import-cookies-bulk', payload),
  startAccountLogin: (payload) => ipcRenderer.invoke('ram:start-account-login', payload),
  searchGames: (payload) => ipcRenderer.invoke('ram:search-games', payload),
  getServers: (payload) => ipcRenderer.invoke('ram:get-servers', payload),
  findPlayerServer: (payload) => ipcRenderer.invoke('ram:find-player-server', payload),
  addFavoriteGame: (payload) => ipcRenderer.invoke('ram:add-favorite-game', payload),
  renameFavoriteGame: (payload) => ipcRenderer.invoke('ram:rename-favorite-game', payload),
  removeFavoriteGame: (payload) => ipcRenderer.invoke('ram:remove-favorite-game', payload),
  getOutfits: (payload) => ipcRenderer.invoke('ram:get-outfits', payload),
  getOutfitDetails: (payload) => ipcRenderer.invoke('ram:get-outfit-details', payload),
  wearAvatarJson: (payload) => ipcRenderer.invoke('ram:wear-avatar-json', payload),
  wearOutfit: (payload) => ipcRenderer.invoke('ram:wear-outfit', payload),
  getAssetDetails: (payload) => ipcRenderer.invoke('ram:get-asset-details', payload),
  purchaseAsset: (payload) => ipcRenderer.invoke('ram:purchase-asset', payload),
  loadControlState: () => ipcRenderer.invoke('ram:load-control-state'),
  addControlledAccounts: (payload) => ipcRenderer.invoke('ram:add-controlled-accounts', payload),
  removeControlledAccounts: (payload) => ipcRenderer.invoke('ram:remove-controlled-accounts', payload),
  updateControlledAccount: (payload) => ipcRenderer.invoke('ram:update-controlled-account', payload),
  saveAccountControlSetting: (payload) => ipcRenderer.invoke('ram:save-account-control-setting', payload),
  getNexusLoader: () => ipcRenderer.invoke('ram:get-nexus-loader'),
  writeNexusLoader: () => ipcRenderer.invoke('ram:write-nexus-loader'),
  updateDynamicControl: (payload) => ipcRenderer.invoke('ram:update-dynamic-control', payload),
  triggerDynamicButton: (payload) => ipcRenderer.invoke('ram:trigger-dynamic-button', payload),
  startNexusServer: () => ipcRenderer.invoke('ram:start-nexus-server'),
  stopNexusServer: () => ipcRenderer.invoke('ram:stop-nexus-server'),
  sendControlCommand: (payload) => ipcRenderer.invoke('ram:send-control-command', payload),
  sendControlScript: (payload) => ipcRenderer.invoke('ram:send-control-script', payload),
  performAction: (payload) => ipcRenderer.invoke('ram:perform-action', payload),
  copyText: (payload) => ipcRenderer.invoke('ram:copy-text', payload),
  accountTool: (payload) => ipcRenderer.invoke('ram:account-tool', payload),
  getAccountDiagnostics: (payload) => ipcRenderer.invoke('ram:get-account-diagnostics', payload),
  debugLog: (payload) => ipcRenderer.invoke('ram:debug-log', payload),
})
